sudo: required

language: go

# start test database
before_install:
  - go get github.com/mattn/goveralls

# go versions to test
go:
  - "1.12.x"

# run tests with coverage
script:
  - make test

after_success:
- bash <(curl -s https://codecov.io/bash)
